ndbench-dyno-plugins/src/main/java/com/netflix/ndbench/plugin/dyno/DynoJedis.java
ndbench-dyno-plugins/src/main/java/com/netflix/ndbench/plugin/dyno/DynoJedisGetSetPipeline.java
ndbench-dyno-plugins/src/main/java/com/netflix/ndbench/plugin/dyno/DynoJedisHashPipeline.java
ndbench-dyno-plugins/src/main/java/com/netflix/ndbench/plugin/local/dynomite/proxy/LocalDynomiteProxyPlugin.java

* Fixing redundant `OperationResult` calls in the `DynoJedisPlugin`.
* Removed the name `plugin` from the titles of the Plugins as it is redundant.
* Added a new plugin that performs Redis `GET`/`SET` inside a pipeline
* Added a new plugin that performs Redis `HMSET`/`HGETALL` inside a pipeline (w/ notes to execute outside of pipeline if needed)

Dyno plugin updates

---

ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/elassandra/ElassandraCassJavaDriverPlugin.java
ndbench-core/src/main/java/com/netflix/ndbench/core/config/NdBenchConfiguration.java
ndbench-core/src/main/java/com/netflix/ndbench/core/defaultimpl/NdBenchGuiceModule.java

@ipapapa @vinaykumarchella 
In regards of https://github.com/Netflix/ndbench/issues/11
I change NdBenchConfiguration to check the available processors and them multiply this result by 4. Doing So I was able to get more than **20K** RPS on Cassandra.
Cheers,
Diego Pacheco

Make Workers aware of CORE Processors

---

ndbench-api/src/main/java/com/netflix/ndbench/api/plugin/NdBenchClientModule.java
ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/elassandra/ElassandraCassJavaDriverPlugin.java
ndbench-core/src/main/java/com/netflix/ndbench/core/discovery/AWSLocalClusterDiscovery.java
ndbench-dyno-plugins/build.gradle
ndbench-dyno-plugins/src/main/java/com/netflix/ndbench/plugin/dyno/DynoJedis.java
ndbench-dyno-plugins/src/main/java/com/netflix/ndbench/plugin/dyno/DynoJedisExtFunc.java
ndbench-dyno-plugins/src/main/java/com/netflix/ndbench/plugin/dyno/DynoJedisGetSetPipeline.java
ndbench-dyno-plugins/src/main/java/com/netflix/ndbench/plugin/dyno/DynoJedisHashPipeline.java
ndbench-dyno-plugins/src/main/java/com/netflix/ndbench/plugin/dyno/DynoJedisUtils.java
ndbench-dyno-plugins/src/main/java/com/netflix/ndbench/plugin/dyno/JedisUtils.java
ndbench-dyno-plugins/src/main/java/com/netflix/ndbench/plugin/local/dynomite/proxy/LocalDynomiteProxyPlugin.java
ndbench-dyno-plugins/src/main/java/com/netflix/ndbench/plugin/local/dynomite/proxy/LocalHttpEndpointBasedTokenMapSupplier.java

* Add a new class that can be used for Functional Testing of several Redis commands such as `GET`/`SET`, pipelines, `HGETALL`/`HMSET`, `ZADD`/`ZRANGE`.
* It centralizes the JedisUtils so they can be used across all Dyno plugins without having to change the core code of each plugin.
* Added proper Javadoc for the Dynomite plugins.
* Updated dyno library to use the latest release.

Adding Extended Functional Testing with JedisUtils

---

ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/cass/CassJavaDriverGeneric.java

Here is the pull request you asked me to create for the batch consistency level bug. setConsistencyLevel needed to be moved from individual statements to the overall batch statement. Note that I also changed the constructor for the batch statement to explicitly specify unlogged batch.  This shouldn't affect anything since Cassandra should not log batches directed to a single partition key anyway, but I thought it was better to be explicit.

Fix batch consistency level bug

---

ndbench-web/src/main/webapp/elements/ndbench-ui-app.html

Clarify that Statistics are gathered per node, not aggregated across client driver instances 
(this confused me when initially trying to interpret the graphs and reports on this panel).

add clarification to title of Instance Statistics dialog [

---

ndbench-es-plugins/src/test/java/com/netflix/ndbench/plugin/es/AbstractPluginIntegrationTest.java
ndbench-es-plugins/src/test/java/com/netflix/ndbench/plugin/es/EsRestPluginIntegrationTest.java

don't rely on CI env vars to disable docker tests.
just disable if  the executables for docker and docker-compose are unavailable

don't rely on CI env vars to disable docker tests.

---

ndbench-core/src/main/java/com/netflix/ndbench/core/DataBackfill.java
ndbench-core/src/main/java/com/netflix/ndbench/core/NdBenchClientFactory.java
ndbench-core/src/main/java/com/netflix/ndbench/core/defaultimpl/NdBenchClientModule.java
ndbench-core/src/main/java/com/netflix/ndbench/core/defaultimpl/NdBenchGuiceModule.java
ndbench-core/src/main/java/com/netflix/ndbench/core/generators/DefaultDataGenerator.java
ndbench-core/src/main/java/com/netflix/ndbench/core/operations/ReadOperation.java
ndbench-core/src/main/java/com/netflix/ndbench/core/operations/WriteOperation.java
ndbench-core/src/main/java/com/netflix/ndbench/core/util/ConstantStepWiseRateIncreaser.java
ndbench-core/src/test/java/com/netflix/ndbench/core/NdbenchDriverTest.java
ndbench-core/src/test/java/com/netflix/ndbench/core/RPSCountTest.java
ndbench-core/src/test/java/com/netflix/ndbench/core/util/ConstantStepWiseRateIncreaserTest.java
ndbench-core/src/test/java/org/libex/logging/log4j/InMemoryAppender.java
ndbench-core/src/test/java/org/libex/test/google/NullPointerTester.java
ndbench-core/src/test/java/org/libex/test/logging/log4j/Log4jCapturer.java
ndbench-es-plugins/src/main/java/com/netflix/ndbench/plugin/es/EsAutoTuner.java
ndbench-es-plugins/src/main/java/com/netflix/ndbench/plugin/es/EsRestPlugin.java
ndbench-es-plugins/src/main/java/com/netflix/ndbench/plugin/es/EsUtils.java
ndbench-es-plugins/src/main/java/com/netflix/ndbench/plugin/es/EsWriter.java
ndbench-es-plugins/src/test/java/com/netflix/ndbench/plugin/es/AbstractPluginTest.java
ndbench-es-plugins/src/test/java/com/netflix/ndbench/plugin/es/AutotuneTest.java
ndbench-geode-plugins/src/main/java/com/netflix/ndbench/geode/plugin/GeodeCloudPlugin.java

- eliminate rate increase table in favor of computing auto tuned rate on the fly using the Gennadiy Formula.
- add additional tests to verify the ability to recover rate ramp-up behavior once error rate falls below threshold after initially exceeding it.

Ditch tmp table for formula

---

ndbench-janusgraph-plugins/src/main/java/com/netflix/ndbench/plugins/janusgraph/JanusGraphPluginCQL.java
ndbench-janusgraph-plugins/src/main/java/com/netflix/ndbench/plugins/janusgraph/configs/IJanusGraphConfig.java

Janusgraph uses Tinkerpop underneath therefore using more representative names as folks may be confused that other than `useTinkerpop` does not use Tinkerpop.

renaming useTinkerpop to useJanusgraphTransaction

---

README.md
build.gradle
ndbench-api/src/main/java/com/netflix/ndbench/api/plugin/common/NdBenchConstants.java
ndbench-core/build.gradle
ndbench-core/src/main/java/com/netflix/ndbench/core/config/IConfiguration.java
ndbench-core/src/test/java/com/ConfigurationPropertiesTest.java
ndbench-janusgraph-plugins/build.gradle
ndbench-web/build.gradle
ndbench-web/src/test/java/com/test/Log4jConfigurationTest.java

* exclude dependencies which bring in a logback implementation so that log4 binding wins
* add allDeps build target to view dependency tree for each sub-project
- updated README to document usage of this feature.
* change string constant for "ndbench.config" property prefix to include "." to decouple from Archaius2 implementation.
DETAILS
change string constant for "ndbench.config" property prefix to include "." to decouple from Archaius2 implementation.
The above mentioned constant resolves to a string that happens to work out because
com.netflix.archaius.ConfigProxyFactory#derivePrefix will append a '.' to a prefix if it is missing.
This change explicitly adds the "." to the constant which is clearer code-wise, and is decoupled from current
implementation of derivePrefix function in …

Dependency excludes ensure slf4j bound to log4j

---

README.md
build.gradle
ndbench-core/build.gradle
ndbench-core/src/main/java/com/netflix/ndbench/core/config/IConfiguration.java
ndbench-core/src/test/java/com/ConfigurationPropertiesTest.java
ndbench-core/src/test/java/com/netflix/ndbench/ConfigurationPropertiesTest.java
ndbench-es-plugins/src/main/java/com/netflix/ndbench/plugin/es/EsRestPlugin.java
ndbench-es-plugins/src/main/java/com/netflix/ndbench/plugin/es/EsWriter.java
ndbench-es-plugins/src/main/java/com/netflix/ndbench/plugin/es/IEsConfig.java
ndbench-es-plugins/src/test/java/com/netflix/ndbench/plugin/es/AbstractPluginTest.java
ndbench-es-plugins/src/test/java/com/netflix/ndbench/plugin/es/ConfigurationPropertiesTest.java
ndbench-janusgraph-plugins/build.gradle
ndbench-web/build.gradle
ndbench-web/src/test/java/com/test/Log4jConfigurationTest.java

This PR should be reviewed once this PR has been merged -> https://github.com/Netflix/ndbench/pull/65  (as it builds on that PR).
DETAILS
Support configuration of timeouts for es plugin.  Default timeout value will reduce number of annoying timeouts occuring in ES benchmarks.
Also, provides end user with configuration knobs to tweak timeout settings on underlying http client connection.

Support configuration of timeouts for es plugin

---

ndbench-es-plugins/build.gradle
ndbench-es-plugins/src/integration-test/java/com.netflix.ndbench.plugin.es/EsIntegrationTest.java
ndbench-es-plugins/src/test/java/com/netflix/ndbench/plugin/es/EsRestPluginIntegrationTest.java

Separation of unit and integration test.  The latter is dependent on  existing of a Docker container.
The value add of this PR is:
- Allow explicit invocation of integration test where appropriate.  The current implementation is always a no-op for builds which results in misleading result.
- Eliminate misleading result by throwing exception when dependency (i.e. Docker) is not available when running integration test.

Separation of unit and integration test

---

ndbench-core/src/main/java/com/netflix/ndbench/core/discovery/AwsAsgDiscovery.java

Currently, in ASG discovery we only load instances from first reservations. I have 4 ndbench nodes in an ASG and 3 of them are loaded in the first batch and the rest one loaded in the last batch, the result is I only get 3 ndbench nodes even I provisioned 4. This PR is addressing this issue.
There are two other improvements for the AWS_ASG discovery:
* Collect public DNS name of ec2 instance instead private IP, so on the UI javascript can make ajax call base on the endpoint
*Sometimes I got duplicate ec2 instances in the cluster member list. Use "Collectors.toSet()" fixed that problem.

Make AWS_ASG discovery find instances cross reservations

---

ndbench-api/src/main/java/com/netflix/ndbench/api/plugin/common/NdBenchConstants.java
ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/cass/CJavaDriverBasePlugin.java
ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/cass/CassJavaDriverManager.java
ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/cass/CassJavaDriverManagerImpl.java
ndbench-core/src/main/java/com/netflix/ndbench/core/defaultimpl/NdBenchGuiceModule.java

Config file discovery exists but it is not enabled in  NdBenchGuiceModule.java class or have a variable assigned in NdBenchConstants.java
This commit enables config file discovery and creates a DISCOVERY_ENV (CONFIG_FILE) variable to enable it during build.

Enabling cluster file config discovery

---

build.gradle
ndbench-cass-plugins/README.md
ndbench-dynamodb-plugins/README.md
ndbench-dynamodb-plugins/build.gradle
ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/DynamoDBKeyValue.java
ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/configs/DynamoDBConfigs.java

* Allowing to use the plugin in two modes: (a) NDBench creating the table; (b) creating the table from AWS Console. The mode is configured by an FP. 
* Fixing the table creation failures in concurrent requests.
* Adding documentation on how to configure DDB.

DDB table configuration

---

ndbench-dynamodb-plugins/build.gradle

Only depend on DynamoDB SDK, not on entire AWS SDK

---

.gitignore
ndbench-api/src/main/java/com/netflix/ndbench/api/plugin/common/NdBenchConstants.java
ndbench-cli/build.gradle
ndbench-cli/src/main/java/com/netflix/ndbench/cli/CliModule.java
ndbench-cli/src/main/java/com/netflix/ndbench/cli/NdbenchCli.java
ndbench-cli/src/main/java/com/netflix/ndbench/cli/config/CliConfigs.java
ndbench-core/src/main/java/com/netflix/ndbench/core/NdBenchDriver.java
ndbench-core/src/main/java/com/netflix/ndbench/core/config/IConfiguration.java
ndbench-core/src/main/java/com/netflix/ndbench/core/generators/RandomStringKeyGenerator.java
ndbench-core/src/main/java/com/netflix/ndbench/core/generators/StringKeyGenerator.java
ndbench-dynamodb-plugins/build.gradle
ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/DynamoDBAutoscalingConfigurer.java
ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/DynamoDBKeyValue.java
ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/configs/DynamoDBConfigs.java
ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/operations/AbstractDynamoDBOperation.java
ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/operations/controlplane/CreateDynamoDBTable.java
ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/operations/controlplane/DescribeLimits.java
ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/operations/dataplane/DynamoDBReadBulk.java
ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/operations/dataplane/DynamoDBReadSingle.java
ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/operations/dataplane/DynamoDBWriteBulk.java
ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/operations/dataplane/DynamoDBWriteSingle.java
settings.gradle

Fixes #131 
I use default values present in the AWS console for all numbers (initial r/w CU, minimum r/w CU, maximum r/w CU and target r/w utilization).

Enable autoscaling when using programmatic tables

---

ndbench-cli/src/main/java/com/netflix/ndbench/cli/NdbenchCli.java
ndbench-cli/src/main/java/com/netflix/ndbench/cli/config/CliConfigs.java

Setup on EC2 Amazon Linux:
```bash
sudo yum update -y \
&& sudo yum upgrade -y \
&& sudo yum install -y java-1.8.0-openjdk-devel git emacs \
&& sudo yum remove -y java-1.7.0-openjdk \
&& git clone https://github.com/amcp/ndbench.git \
&& cd ndbench \
&& git checkout cli \
&& ./gradlew build
```
Test 1:
```bash
DISCOVERY_ENV=AWS ./gradlew run \
-Dndbench.config.cli.clientName=DynamoDBKeyValue \
-Dndbench.config.cli.bulkSize=1 \
-Dndbench.config.cli.timeoutMillis=180000 \
-Dndbench.config.dataSize=1000 \
-Dndbench.config.numKeys=1 \
-Dndbench.config.readEnabled=true \
-Dndbench.config.readRateLimit=20000 \
-Dndbench.config.writeEnabled=true \
-Dndbench.config.writeRateLimit=20000 \
-Dndbench.config.dynamodb.rcu=20000 \
-Dndbench.config.dynamodb.wcu=20000 \ …
```

Add cli driver for all clients

---

ndbench-dynamodb-plugins/build.gradle
ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/DynamoDBKeyValue.java
ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/DynamoDBKeyValueBase.java
ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/DynamoDBProgrammaticKeyValue.java
ndbench-dynamodb-plugins/src/test/java/com/netflix/ndbench/plugin/dynamodb/DynamoDBProgrammaticKeyValueTest.java

This change adds some tests to the DynamoDB module, demonstrates testing with DynamoDB local and Gradle, and fixes some null pointer exceptions in DynamoDBProgrammaticKeyValue related to the fact that the encapsulated KeyValue was not delegated to for writeOnce, writeBulk, readOnce, and readBulk

Add some code verification tests to the programmatic DynamoDB module

---

ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/cass/CassAstyanaxPlugin.java
ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/configs/CassandraAstynaxConfiguration.java
ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/configs/CassandraConfigurationBase.java
ndbench-cass-plugins/src/main/resources/setupCassTables.cql
ndbench-core/src/main/java/com/netflix/ndbench/core/config/GuiceInjectorProvider.java
ndbench-evcache-plugins/src/main/java/com/netflix/ndbench/plugin/evcache/configs/EVCachePluginModule.java
ndbench-web/src/main/java/com/netflix/ndbench/core/config/WebGuiceInjectorProvider.java
ndbench-web/src/main/java/com/netflix/ndbench/defaultimpl/InjectedWebListener.java
ndbench-web/src/main/resources/laptop.properties

- Fixed ndbench-evcache-plugin issues preventing NdBench from successfully starting in local env and preventing extensions from setting a different LookupService impl.
- Changed defaults of ndbench-cass-plugins to consistently support running in local env (most of the defaults already supported local env, but a few did not).

Running locally and using custom LookupService impl

---

ndbench-aws/src/main/java/com/netflix/ndbench/aws/defaultimpl/AwsDefaultsModule.java
ndbench-dax-plugins/src/main/java/com/netflix/ndbench/plugin/dax/configs/DaxModule.java
ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/configs/DynamoDBModule.java

Remove the aws module dependency for config initialization in dax and dynamo modules

Remove the aws module dependency for config initialization in dax and dynamo modules

---

ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/cass/CassAstyanaxPlugin.java
ndbench-core/src/main/java/com/netflix/ndbench/core/config/IConfiguration.java
ndbench-core/src/main/java/com/netflix/ndbench/core/generators/DefaultDataGenerator.java
ndbench-core/src/main/java/com/netflix/ndbench/core/util/CheckSumUtil.java
ndbench-core/src/test/java/com/netflix/ndbench/core/util/ChecksumUtilTest.java
ndbench-es-plugins/src/test/java/com/netflix/ndbench/plugin/es/AbstractPluginTest.java

This feature adds the capability to do checksum validation for "values". Checksum can be included into the values by the DefaultDataGenerator based on a configurable value, and a reader can choose to validate the checksum of the value read, based on a configurable value.
Having this capability is useful to validate, say, the correctness of a datastore, at least in terms of corruption of the values being written.

Adding checksum validation capability

---

ndbench-core/src/main/java/com/netflix/ndbench/core/DataBackfill.java

Removing retries on backfill operation failures, since it could lead to long-running backfill operations.

Removing retries on backfill operation failures

---

ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/cass/CassJavaDriverGeneric.java
ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/configs/CassandraGenericConfiguration.java

The use of `BATCH` in `CassJavaDriverGeneric` allows the driver to write multiple rows in a single call to `writeSingle`. Its sometimes desirable, however, to have `writeSingle` to truly write a single row so that `BATCH` is not used.
This can cause the row count validation to fail since not every row is written to every partition. An additional configuration has been added to disable this validation.

CassJavaDriverGeneric: add options to disable use of batch writes

---

ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/datastax4/CJavaDriverBasePlugin.java

remove the log for protocol version, this config is not required value and won't exist in a lot of cases. Having this log will require this value to be set otherwise there will be config not exist error.

remove log for protocol version
