LICENSE
README.md

We have forgotten the Apache License :)

adding Apache License

---

ndbench-es-plugins/build.gradle
ndbench-es-plugins/src/main/java/com/netflix/ndbench/plugin/es/EsPlugin.java
ndbench-web/build.gradle
settings.gradle

Adding ElasticSearch Plugin

---

ndbench-core/build.gradle
ndbench-core/src/main/java/com/netflix/ndbench/core/discovery/LocalClusterDiscovery.java
ndbench-web/build.gradle

Also, move `genson` serialization library to web project,

Fix localhost connection issues when hostname is not resolved

---

build.gradle
ndbench-api/src/main/java/com/netflix/ndbench/api/plugin/NdBenchClient.java
ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/cass/CassAstyanaxPlugin.java
ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/cass/CassJavaDriverPlugin.java
ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/elassandra/ElassandraCassJavaDriverPlugin.java
ndbench-cass-plugins/src/main/resources/setupCassTables.cql
ndbench-core/build.gradle
ndbench-core/src/main/java/com/netflix/ndbench/core/NdBenchDriver.java
ndbench-core/src/main/java/com/netflix/ndbench/core/generators/DefaultDataGenerator.java
ndbench-dyno-plugins/src/main/java/com/netflix/ndbench/plugin/dyno/DynoJedis.java
ndbench-dyno-plugins/src/main/java/com/netflix/ndbench/plugin/dyno/DynoJedisExtFunc.java
ndbench-dyno-plugins/src/main/java/com/netflix/ndbench/plugin/dyno/DynoJedisGetSetPipeline.java
ndbench-dyno-plugins/src/main/java/com/netflix/ndbench/plugin/dyno/DynoJedisHashPipeline.java
ndbench-dyno-plugins/src/main/java/com/netflix/ndbench/plugin/local/dynomite/proxy/LocalDynomiteProxyPlugin.java
ndbench-es-plugins/src/main/java/com/netflix/ndbench/plugin/es/EsPlugin.java
ndbench-sample-plugins/src/main/java/com/netflix/ndbench/plugin/sample/InMemoryTestPlugin.java

Adding PropertyFactory to plugins so that any random properties can be accessed in plugins.

Adding PropertyFactory to plugins

---

build.gradle
ndbench-api/src/main/java/com/netflix/ndbench/api/plugin/NdBenchClient.java
ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/cass/CassAstyanaxPlugin.java
ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/cass/CassJavaDriverPlugin.java
ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/elassandra/ElassandraCassJavaDriverPlugin.java
ndbench-cass-plugins/src/main/resources/setupCassTables.cql
ndbench-core/build.gradle
ndbench-core/src/main/java/com/netflix/ndbench/core/NdBenchDriver.java
ndbench-core/src/main/java/com/netflix/ndbench/core/generators/DefaultDataGenerator.java
ndbench-dyno-plugins/src/main/java/com/netflix/ndbench/plugin/dyno/DynoJedis.java
ndbench-dyno-plugins/src/main/java/com/netflix/ndbench/plugin/dyno/DynoJedisExtFunc.java
ndbench-dyno-plugins/src/main/java/com/netflix/ndbench/plugin/dyno/DynoJedisGetSetPipeline.java
ndbench-dyno-plugins/src/main/java/com/netflix/ndbench/plugin/dyno/DynoJedisHashPipeline.java
ndbench-dyno-plugins/src/main/java/com/netflix/ndbench/plugin/local/dynomite/proxy/LocalDynomiteProxyPlugin.java
ndbench-es-plugins/src/main/java/com/netflix/ndbench/plugin/es/EsPlugin.java
ndbench-sample-plugins/src/main/java/com/netflix/ndbench/plugin/sample/InMemoryTestPlugin.java

Revert "Adding PropertyFactory to plugins"

---

ndbench-cass-plugins/README.md
ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/cass/CJavaDriverBasePlugin.java
ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/cass/CassBatch.java
ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/cass/CassJavaDriverBatch.java
ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/cass/CassJavaDriverGeneric.java
ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/cass/CassJavaDriverManager.java
ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/cass/CassJavaDriverManagerImpl.java
ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/cass/CassJavaDriverPlugin.java
ndbench-cass-plugins/src/main/resources/setupCassTables.cql

Adding 2 more C* JavaDriver related plugins
1. CassJavaDriverGeneric
2. CassJavaDriverBatch

Adding 2 more C* JavaDriver related plugins

---

ndbench-core/src/main/java/com/netflix/ndbench/core/NdBenchClientFactory.java

remove redundant @Inject on field which is set in constructor that also has an @Inject

remove redundant @Inject on field which is set in constructor that also has an @Inject

---

ndbench-core/src/main/java/com/netflix/ndbench/core/NdBenchDriver.java

remember when I got confused about where the bottleneck was with the rate limiter ?      This warning message might help point your less clueful users (like me!) in the right direction to debug this kind of problem.

Better err msg if rate not keeping up

---

README.md
ndbench-core/src/main/java/com/netflix/ndbench/core/defaultimpl/NdBenchGuiceModule.java

All default properties should be for local deployment.

Clarifying loading modules

---

ndbench-core/src/main/java/com/netflix/ndbench/core/discovery/AWSLocalClusterDiscovery.java
ndbench-core/src/main/java/com/netflix/ndbench/core/discovery/CfClusterDiscovery.java
ndbench-core/src/main/java/com/netflix/ndbench/core/discovery/ConfigFileDiscovery.java
ndbench-core/src/main/java/com/netflix/ndbench/core/discovery/IClusterDiscovery.java
ndbench-core/src/main/java/com/netflix/ndbench/core/discovery/LocalClusterDiscovery.java
ndbench-core/src/main/java/com/netflix/ndbench/core/resources/NDBenchClusterResource.java

Remove hardcoded port number in cluster/list api

Remove hardcoded port number in cluster/list api

---

build.gradle

Updated netflixoss plugin to 4.0.1, which fixes the confusing NPE reported on #39. 
Updated Gretty to 2.0.0, which works better with Gradle 4.+

Fix NPE Reported on Issue #39

---

ndbench-core/src/main/java/com/netflix/ndbench/core/discovery/AWSLocalClusterDiscovery.java

Fix metadata URL reported in #47

fix metadata link

---

ndbench-janusgraph-plugins/src/main/java/com/netflix/ndbench/plugins/janusgraph/JanusGraphPluginCQL.java

* Fixing the transaction leak
* Simplify the `JanusGraphTransaction` implicit call.

Simplify Janusgraph transactions and APIs

---

ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/DynamoDBKeyValue.java
ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/configs/DynamoDBConfigs.java
ndbench-evcache-plugins/src/main/java/com/netflix/ndbench/plugin/evcache/EVCacheTestPlugin.java
ndbench-evcache-plugins/src/main/java/com/netflix/ndbench/plugin/evcache/configs/EVCacheConfigs.java
ndbench-evcache-plugins/src/main/java/com/netflix/ndbench/plugin/evcache/configs/EVCacheModule.java

Cleaning the EVCache configurations and creating a new interface were all configurations can be inserted.

EVCache configurations

---

ndbench-api/src/main/java/com/netflix/ndbench/api/plugin/common/NdBenchConstants.java
ndbench-core/build.gradle
ndbench-core/src/main/java/com/netflix/ndbench/core/NdBenchDriver.java
ndbench-core/src/main/java/com/netflix/ndbench/core/config/IConfiguration.java
ndbench-core/src/main/java/com/netflix/ndbench/core/generators/KeyGeneratorFactory.java
ndbench-core/src/main/java/com/netflix/ndbench/core/generators/ZipfianStringKeyGenerator.java
ndbench-core/src/main/java/com/netflix/ndbench/core/util/LoadPattern.java
ndbench-es-plugins/src/test/java/com/netflix/ndbench/plugin/es/AbstractPluginTest.java
ndbench-sample-plugins/build.gradle
ndbench-web/src/main/webapp-src/app/elements/ndb-driver-settings.html
ndbench-web/src/main/webapp/elements/ndbench-ui-app.html

This adds a new generator for simulating cache friendly workloads.

Adds the zipfian generator into Open Source NDBench

---

ndbench-api/src/main/java/com/netflix/ndbench/api/plugin/NdBenchClient.java
ndbench-evcache-plugins/build.gradle

Fix the build by adding defaults for bulk endpoints

---

ndbench-api/src/main/java/com/netflix/ndbench/api/plugin/common/InstanceDiscovery.java
ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/cass/CassJavaDriverGeneric.java
ndbench-core/src/main/java/com/netflix/ndbench/core/config/GuiceInjectorProvider.java
ndbench-core/src/main/java/com/netflix/ndbench/core/util/ConstantStepWiseRateIncreaser.java
ndbench-es-plugins/src/main/java/com/netflix/ndbench/plugin/es/EsAutoTuner.java
ndbench-es-plugins/src/main/java/com/netflix/ndbench/plugin/es/EsRestPlugin.java
ndbench-es-plugins/src/main/java/com/netflix/ndbench/plugin/es/EsUtils.java
ndbench-es-plugins/src/main/java/com/netflix/ndbench/plugin/es/EsWriter.java
ndbench-es-plugins/src/main/java/com/netflix/ndbench/plugin/es/FakeWordDictionaryBasedDataGenerator.java
ndbench-es-plugins/src/main/java/com/netflix/ndbench/plugin/es/IEsConfig.java
ndbench-es-plugins/src/main/java/com/netflix/ndbench/plugin/es/NfndbenchEsModule.java
ndbench-es-plugins/src/main/java/com/netflix/ndbench/plugin/es/WriteResult.java
ndbench-evcache-plugins/src/main/java/com/netflix/ndbench/plugin/evcache/EVCacheTestPlugin.java

Attempts to fix build and adds missing license header where necessary.

Fix missing license headers

---

ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/DynamoDBKeyValue.java
ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/configs/DynamoDBConfigs.java

Wires DynamoDB configuration options (gzip, maxconn, region, endpoint)

---

ndbench-core/src/main/java/com/netflix/ndbench/core/NdBenchDriver.java

Log statement report thread stopped not process

---

ndbench-core/src/main/java/com/netflix/ndbench/core/NdBenchDriver.java

Factor out constant for timeout in stopOperation

---

ndbench-core/src/main/java/com/netflix/ndbench/core/NdBenchDriver.java

Make sure keys in batch are unique

---

ndbench-core/src/main/java/com/netflix/ndbench/core/NdBenchDriver.java

Publish average latency along with TPS in RPSCount

---

ndbench-core/src/main/java/com/netflix/ndbench/core/NdBenchDriver.java
ndbench-core/src/test/java/com/netflix/ndbench/core/RPSCountTest.java

Condition tps warnings on whether the operation is enabled

---

ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/cass/CassJavaDriverBatch.java
ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/cass/CassJavaDriverGeneric.java
ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/cass/CassJavaDriverManager.java
ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/cass/CassUDTFrozen.java
ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/elassandra/ElassandraCassJavaDriverPlugin.java
ndbench-core/src/main/java/com/netflix/ndbench/core/config/GuiceInjectorProvider.java
ndbench-es-plugins/src/main/java/com/netflix/ndbench/plugin/es/EsRestPlugin.java
ndbench-es-plugins/src/test/java/com/netflix/ndbench/plugin/es/ConfigurationPropertiesTest.java
ndbench-es-plugins/src/test/java/com/netflix/ndbench/plugin/es/EsRestPluginIntegrationTest.java
ndbench-geode-plugins/src/main/java/com/netflix/ndbench/plugin/geode/GeodeCloudPlugin.java
ndbench-sample-plugins/src/main/java/com/netflix/ndbench/plugin/sample/InMemoryTestPlugin.java

Remove unused imports

---

ndbench-core/src/main/java/com/netflix/ndbench/core/generators/RandomStringKeyGenerator.java
ndbench-core/src/main/java/com/netflix/ndbench/core/generators/SlidingWindowFlipStringKeyGenerator.java
ndbench-core/src/main/java/com/netflix/ndbench/core/generators/SlidingWindowStringKeyGenerator.java
ndbench-core/src/main/java/com/netflix/ndbench/core/generators/StringKeyGenerator.java
ndbench-core/src/main/java/com/netflix/ndbench/core/generators/ZipfianStringKeyGenerator.java

Refactor KeyGenerators for more code reuse

---

ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/DynamoDBKeyValue.java

Fix NPE after catching a Client/Service exception

---

ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/DynamoDBKeyValue.java

Make the SDK clients and related objects member fields

---

ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/DynamoDBKeyValue.java

Use partition key name from config

---

ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/DynamoDBKeyValue.java

Implemented bulk read/write with BatchGet/Write APIs

---

ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/DynamoDBKeyValue.java
ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/configs/DynamoDBConfigs.java

Add max retries and max request timeout to config

---

README.md
ndbench-dynamodb-plugins/README.md

Fix spelling of DynamoDB and correct trade name

---

ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/DynamoDBKeyValue.java

[DynamoDB] Use the vanilla sdk for data plane operations

---

ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/DynamoDBKeyValue.java

[DynamoDB] Fix consistent read setting for read bulk

---

ndbench-core/src/main/java/com/netflix/ndbench/core/NdBenchDriver.java
ndbench-core/src/main/java/com/netflix/ndbench/core/RPSCount.java
ndbench-core/src/test/java/com/netflix/ndbench/core/RPSCountTest.java

Move RPSCount to a separate file

---

ndbench-core/src/main/java/com/netflix/ndbench/core/operations/ReadOperation.java
ndbench-core/src/main/java/com/netflix/ndbench/core/operations/WriteOperation.java
ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/DynamoDBKeyValue.java

Reduce console output for throttling exceptions

---

ndbench-dynamodb-plugins/build.gradle
ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/DynamoDBKeyValue.java
ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/NdbenchAWSCredentialProvider.java
ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/configs/DynamoDBConfiguration.java
ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/configs/DynamoDBModule.java
ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/operations/AbstractDynamoDBOperation.java
ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/operations/controlplane/CreateDynamoDBTable.java
ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/operations/controlplane/DeleteDynamoDBTable.java
ndbench-dynamodb-plugins/src/test/java/com/netflix/ndbench/plugin/dynamodb/configs/DynamoDBConfigurationTest.java
ndbench-dynamodb-plugins/src/test/java/com/netflix/ndbench/plugin/dynamodb/operations/controlplane/CreateTableTest.java
ndbench-dynamodb-plugins/src/test/java/com/netflix/ndbench/plugin/dynamodb/operations/controlplane/DeleteTableTest.java

[DynamoDB] Added jacoco and tested control plane operations

---

ndbench-cli/build.gradle
ndbench-dynamodb-plugins/README.md
ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/DaxKeyValue.java
ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/DynamoDBKeyValue.java
ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/DynamoDBKeyValueBase.java
ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/DynamoDBProgrammaticKeyValue.java
ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/NdbenchAWSCredentialProvider.java
ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/configs/CredentialsConfiguration.java
ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/configs/DaxConfiguration.java
ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/configs/DynamoDBConfigurationBase.java
ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/configs/DynamoDBModule.java
ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/configs/ProgrammaticDynamoDBConfiguration.java
ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/operations/AbstractAwsOperation.java
ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/operations/dynamodb/AbstractDynamoDBOperation.java
ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/operations/dynamodb/controlplane/DescribeLimits.java
ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/operations/dynamodb/dataplane/AbstractDynamoDBDataPlaneOperation.java
ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/operations/dynamodb/dataplane/CapacityConsumingFunction.java
ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/operations/dynamodb/dataplane/DynamoDBReadBulk.java
ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/operations/dynamodb/dataplane/DynamoDBReadSingle.java
ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/operations/dynamodb/dataplane/DynamoDBWriteBulk.java
ndbench-dynamodb-plugins/src/main/java/com/netflix/ndbench/plugin/dynamodb/operations/dynamodb/dataplane/DynamoDBWriteSingle.java
ndbench-dynamodb-plugins/src/test/java/com/netflix/ndbench/plugin/dynamodb/configs/DaxConfigurationTest.java
ndbench-dynamodb-plugins/src/test/java/com/netflix/ndbench/plugin/dynamodb/configs/ProgrammaticDynamoDBConfigurationTest.java

[DynamoDB] Separate Dax, programmatic tables into different client, update README.md

---

build.gradle
ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/cass/CJavaDriverBasePlugin.java
ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/cass/CassAstyanaxPlugin.java
ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/cass/CassJavaDriverBatch.java
ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/cass/CassJavaDriverGeneric.java
ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/cass/CassUDTFrozen.java
ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/configs/CassModule.java
ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/configs/CassandraAstynaxConfiguration.java
ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/configs/CassandraConfigurationBase.java
ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/configs/CassandraGenericConfiguration.java
ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/configs/CassandraUdtConfiguration.java
ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/configs/ElassandraConfiguration.java
ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/elassandra/ElassandraCassJavaDriverPlugin.java
ndbench-core/src/main/java/com/netflix/ndbench/core/NdBenchDriver.java
ndbench-core/src/main/java/com/netflix/ndbench/core/discovery/LocalClusterDiscovery.java
ndbench-core/src/main/java/com/netflix/ndbench/core/resources/NdBenchResource.java
ndbench-geode-plugins/src/main/java/com/netflix/ndbench/plugin/geode/GeodeCloudPlugin.java
ndbench-janusgraph-plugins/src/main/java/com/netflix/ndbench/plugin/janusgraph/JanusGraphBasePlugin.java
ndbench-janusgraph-plugins/src/main/java/com/netflix/ndbench/plugin/janusgraph/JanusGraphPluginCQL.java
ndbench-janusgraph-plugins/src/main/java/com/netflix/ndbench/plugin/janusgraph/cql/JanusGraphBuilderCQLProvider.java

Fix all PMD warnings throughout all modules

---

build.gradle
ndbench-dax-plugins/README.md
ndbench-dax-plugins/build.gradle
ndbench-dax-plugins/src/main/java/com/netflix/ndbench/plugin/dax/DaxKeyValue.java
ndbench-dax-plugins/src/main/java/com/netflix/ndbench/plugin/dax/configs/DaxConfiguration.java
ndbench-dax-plugins/src/main/java/com/netflix/ndbench/plugin/dax/configs/DaxModule.java
ndbench-dax-plugins/src/test/java/com/netflix/ndbench/plugin/dax/configs/DaxConfigurationTest.java
ndbench-dynamodb-plugins/README.md
settings.gradle

Split DynamoDB and DAX plugins

---

ndbench-dax-plugins/build.gradle
settings.gradle

Enable DAX plugin and depend on client in Maven

---

ndbench-cass-plugins/build.gradle
ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/configs/CassandraAstynaxConfiguration.java
ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/configs/CassandraGenericConfiguration.java
ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/configs/ElassandraConfiguration.java
ndbench-cass-plugins/src/main/resources/setupCassTables.cql

Fix some minor issues discovered while executing ndbench on localhost.

Local test

---

ndbench-core/src/main/java/com/netflix/ndbench/core/DataBackfill.java
ndbench-core/src/main/java/com/netflix/ndbench/core/resources/NdBenchResource.java
ndbench-core/src/test/java/com/netflix/ndbench/core/DataBackfillTest.java
ndbench-core/src/test/java/com/netflix/ndbench/core/NdbenchDriverTest.java

Fixing Databackfill bug - Restarting backfill works now.

 Fixing Databackfill bug - Restarting backfill works now.

---

ndbench-cass-plugins/build.gradle
ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/cass/CJavaDriverBasePlugin.java
ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/cass/CassJavaDriverBatch.java
ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/cass/CassJavaDriverGeneric.java
ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/cass/CassUDTFrozen.java
ndbench-core/build.gradle
ndbench-core/src/main/java/com/netflix/ndbench/core/DataBackfill.java
ndbench-core/src/main/java/com/netflix/ndbench/core/config/IConfiguration.java
ndbench-core/src/main/java/com/netflix/ndbench/core/generators/DefaultDataGenerator.java
ndbench-core/src/test/java/com/netflix/ndbench/core/DataBackfillTest.java
ndbench-es-plugins/src/test/java/com/netflix/ndbench/plugin/es/AbstractPluginTest.java

Backfill improvements to make it load faster

Backfill improvements to make it load faster

---

ndbench-cass-plugins/src/main/java/com/netflix/ndbench/plugin/cass/CassJavaDriverGeneric.java
ndbench-core/build.gradle
ndbench-core/src/main/java/com/netflix/ndbench/core/DataBackfill.java
ndbench-core/src/main/java/com/netflix/ndbench/core/util/NdbUtil.java
ndbench-core/src/test/java/com/netflix/ndbench/core/util/NdbUtilTest.java

Simplify the data size calculations in CassJavaDriverGeneric plugin

Simplify the data size calculations in CassJavaDriverGeneric plugin

---

ndbench-cockroachdb-plugins/build.gradle
ndbench-cockroachdb-plugins/src/main/java/com/netflix/ndbench/plugin/cockroachdb/configs/CockroachDBConfiguration.java
ndbench-cockroachdb-plugins/src/main/java/com/netflix/ndbench/plugin/cockroachdb/operations/CockroachDBPluginBase.java
ndbench-cockroachdb-plugins/src/main/java/com/netflix/ndbench/plugin/cockroachdb/operations/CockroachDBRetryableTransaction.java
ndbench-cockroachdb-plugins/src/main/java/com/netflix/ndbench/plugin/cockroachdb/operations/CockroachDBSecondaryIndexPlugin.java
ndbench-cockroachdb-plugins/src/main/java/com/netflix/ndbench/plugin/cockroachdb/operations/CockroachDBSimplePlugin.java
ndbench-cockroachdb-plugins/src/main/java/com/netflix/ndbench/plugin/cockroachdb/operations/CockroachDBTransactionPlugin.java

This PR introduces a thread pool which will increase overall throughput and allow for multiple transactions to occur across threads. The transaction retry logic has also been refactored.

Added a connection pool along with the ability to retry transactions.

---

ndbench-core/src/main/java/com/netflix/ndbench/core/resources/NdBenchResource.java
ndbench-core/src/main/java/com/netflix/ndbench/core/util/RestUtil.java

Enhanced error message. Added additional detailedMessage field to have an excerpt of the exception to help with debugging.

Enhanced error message. Added detailedMessage field in error response with exception stack trace.
